name: git-action-workflow
on:
    push: 
        branches: 
            - main
    pull_request: 
        branches: 
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Run commands
              run:
                ls -al
    
